### ISSUE TITLE
MSVC unresolved external symbol "wase-engine-stuff"

### ISSUE THREAD

**Issue by requizm** [JelleVos1/simon#2]
I built the wase-engine without any problems. The following files were created:
-lib/x86/debug/wase-engine.lib
-lib/x86/debug/wase-engine.pdb
-include/**

Then i tried to build simon.  
"cmake .. -D WASE_ENGINE_INCLUDE_DIR=path/include -D WASE_ENGINE_LIBRARIES=path/wase-engine.lib"  
  
But i get this errors:
<details>
  <summary>Errors</summary>
  
  ```
  Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: __thiscall AudioSource::AudioSource(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned char,bool,bool)" (??0AudioSource@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@E_N1@Z) referenced in function "public: class AudioSource * __thiscall Entity::addComponent<class AudioSource,char const (&)[9]>(char const (&)[9])" (??$addComponent@VAudioSource@@AAY08$$CBD@Entity@@QAEPAVAudioSource@@AAY08$$CBD@Z)	simon	C:\Users\mehme\Documents\Projects\simon-master\build\game_manager.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: void __thiscall AudioSource::play(void)" (?play@AudioSource@@QAEXXZ) referenced in function "private: void __thiscall GameManager::addColor(int)" (?addColor@GameManager@@AAEXH@Z)	simon	C:\Users\mehme\Documents\Projects\simon-master\build\game_manager.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual void __thiscall AudioSource::onStateChange(bool)" (?onStateChange@AudioSource@@UAEX_N@Z)	simon	C:\Users\mehme\Documents\Projects\simon-master\build\game_manager.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: virtual void __thiscall AudioSource::destroy(void)" (?destroy@AudioSource@@UAEXXZ)	simon	C:\Users\mehme\Documents\Projects\simon-master\build\game_manager.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	4 unresolved externals	simon	C:\Users\mehme\Documents\Projects\simon-master\build\Debug\simon.exe	1
  ```
</details>
  
I'm pretty sure it's not a problem of not being able to find the lib file. This error would normally be received either when the lib file does not exist or the architecture(x86-x64) of the lib file is incorrect. But wase-engine and simon using win32(x86) build. Am i missing something?

**System information:**
 - OS: Windows 10
 - Version: 20H2

**Comment by TessaVos** [comment]
Thank you very much for the issue! I accidentally forgot to add 2 files to the CMakeLists.txt and that resulted into the lib not being complete. With the new tag of Wase Engine that you can get in the [repository](https://github.com/Wase-Engine/wase-engine/releases/tag/1.0) or on the [website](https://wase-engine.com/) it should work fine and you should be able to play the game.

Thank you for your interest in my projects!
